theme: jekyll-theme-cayman

title: Social Graphs Project
#tagline: Are movies the same?
description: Are movies different?

exclude: ["README.md", "Rakefile", "License.md"]

markdown: kramdown
kramdown:
  parse_block_html: true
